#!/bin/sh
#
# A SysV init script to manage the OWL API.
#
# Written by Sam Artuso <sam@highoctanedev.co.uk>
# and extensively based on https://gist.github.com/naholyr/4275302

### BEGIN INIT INFO
# Provides:          owl-api
# Required-Start:    $network $local_fs mongodb
# Required-Stop:     $network $local_fs mongodb
# Should-Start:      $named
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: The OWL API.
### END INIT INFO

ENVIRONMENT='staging'
SCRIPT=/srv/owl/api/$ENVIRONMENT/bin/www
RUNAS=owlapi

PIDFILE=/var/run/owl-api.$ENVIRONMENT.pid
LOGFILE=/var/log/owl-api.$ENVIRONMENT.log

start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service...' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started.' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service...' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped.' >&2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
