export const REQUEST_PATCHES = 'REQUEST_PATCHES';
export const RECEIVE_PATCHES = 'RECEIVE_PATCHES';

export const REQUEST_AUTHORS = 'REQUEST_AUTHORS';
export const RECEIVE_AUTHORS = 'RECEIVE_AUTHORS';

export const REQUEST_TAGS = 'REQUEST_TAGS';
export const RECEIVE_TAGS = 'RECEIVE_TAGS';

export const REQUEST_CURRENT_USER = 'REQUEST_CURRENT_USER';
export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER';

export const SET_PATCHLIST_TOP_FILTER = 'SET_PATCHLIST_TOP_FILTER';

export const TOGGLE_FILTER_IN_SUB_FILTER = 'TOGGLE_FILTER_IN_SUB_FILTER';
export const RESET_PATCHLIST_SUB_FILTER = 'RESET_PATCHLIST_SUB_FILTER';
export const ADD_TO_INITIAL_CACHED_SUB_FILTER = 'ADD_TO_INITIAL_CACHED_SUB_FILTER';

export const API_END_POINT = '//' + window.location.host + '/api';