#!/bin/bash
# Written by Sam Artuso <sam@highoctanedev.co.uk>

DATABASE="owl_production"
BACKUP_FILE="mongo.owl_production.$(date +%Y-%m-%d).tar.bz2"
DST_DIR="/var/backups/owl/mongo"

cd /tmp
mongodump -d $DATABASE
tar -cjf $BACKUP_FILE dump
mv $BACKUP_FILE $DST_DIR
find $DST_DIR -mtime +30 -exec rm -f '{}' \;
